default_platform(:android)

platform :android do
  
  desc "Deploy to Internal Testing"
  lane :internal do
    gradle(
      task: "bundle",
      build_type: "Release"
    )
    
    upload_to_play_store(
      track: 'internal',
      aab: "../app/build/outputs/bundle/release/app-release.aab",
      json_key: "./fastlane/play-store-key.json",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
  
end
