default_platform(:android)

platform :android do
  
  desc "Deploy to Internal Testing"
  lane :internal do
    # AAB file path
    aab_path = "../composeApp/build/outputs/bundle/release/composeApp-release.aab"
    
    # Upload to Play Store
    upload_to_play_store(
      track: 'internal',
      aab: aab_path,
      json_key: "./fastlane/play-store-key.json",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
  
end
